### ISSUE TITLE
Manuális tesztek megtervezése, végrehajtása és dokumentálása

### ISSUE THREAD

**Issue by diatrcz** [BME-MIT-IET/iet-hf-2023-syntax-spuad#3]
Manuális tesztek megtervezése, végrehajtása és dokumentálása.

**Comment by Randomlosz** [comment]
Ezt a feladatot a csapattal való egyeztetés után, rám osztottuk ki.

**Comment by Randomlosz** [comment]
1. teszt:
A hozzárendelt pull-request a következő teszthez tartozik: megpróbáltam betelíteni a tárhelyet felszerelésekből, és ekkor felvenni egy elemet. Ez példánkban egy kabát volt, ilyenkor az elvárt viselkedés szerint annak a pályán kell maradnia, hisz nincs helyünk felvenni. 
Ez így is történt, mind logikailag mind grafikailag a pályán maradt a felszerelés, csupán a konzolon a visszajelzés volt hibás. "cloat added." üzenetet kaptunk, amit csak ezekben az esetekben átírtam "EquipmentPocket is full." üzenetre, hasonlóan ahhoz, ahogy a teli ElementBank kerül jelzésre. Így sikertelen felszerelés felvételek esetén, már erről értesít a konzol.
Ez a változás, javítás jelenik meg a "BackPack.add( ) televan hibajelzes" nevű pull-requestben.

**Comment by Randomlosz** [comment]
2. teszt:
Megpróbáltam hasonlóképpen megtelíteni az ElementBank bankot is, hátha ott is bukkanok hasonló hibára, azonban ott figyelmeztet minket ha nem tudunk már felvenni többet, mert televan a tárhelyünk. Az anyagmennyiség a pályán marad. Így tehát az anyag-tárhely megtelítésénél ebből a szempontból az elvárt viselkedést tapasztaltam.

**Comment by Randomlosz** [comment]
3. teszt:
Az előző vizsgálata közben bukkantam arra a jelenségre, hogy bár legtöbbször jól működik, bizonyos esetekben (általában mikor már az adott körben léptünk) az anyagot ha felvesszük a mezőről, az nem tűnik el onnan. (Ez egy sor további bugghoz vezet a következő körökben: vagy tele tárhelyre hivatkozik, pedig csak elfogyott a lépésünk, vagy egymás után többször kiírja, hogy felvettük, pedig nem is. Egy logikailag üres raktár marad ott ilyenkor, grafikailag megjelenítve, körökön át, szóval nem csak késik a képernyőfrissítés.)
A viselkedést vizsgálni kezdtem, szemet szúrt, hogy ilyenkor mindig 40 körüli értékre ugranak a számok a birtokolt anyagmennyiségnél. Eredetileg is sejteni lehetett, hogy az anyag raktár valahol nem kerül törlésre, nem lesz levéve a pályáról, kiürítve, vagy valamilyen, bármilyen módon jelezve, hogy az anyag az adott mezőn elfogyott.

Hosszas vizsgálat után átnéztem több ide tartozó osztályt, és több javítási lehetőséget. Kerestem, hogyan lehet, hogy a felszereléseknél rendeltetés szerűen működik ugyanezen funkció, azt próbáltam alapul venni.
Több eltérés van, a felszerelés pontosabban van kezelve a kódban, és valamellyest pontosabb vizsgálatot is ígényel az ottani szempontok szerint. Azonban, bár ezen eltérések jelentős része nem okoz problémát, megtaláltam a kódrészletet, ahol a "Virologist.pickUpEquipment( )" törli a felvett elemet a hozzátartozó "field"-ről, ami történetesen egy "SafeHouse" osztály.

Ennek mentén, a "Virologist.pickUpMaterial( )" függvénynek feltételeztem, hogy törölnie kéne a megadott "field"-ről a teljesen kiürített anyagraktárat (ami némely esetekben meg is történik a játék közben), így elérve hogy ne okozzon később üres léte problémát. Ez a speciális "field" a "StoreHouse" osztály, melynek meg is volt a függvénye, amivel kiüríthető a rajta lévő raktár. 

Csupán ennek meghívásával, már nem tapasztalom tovább az említett hibát, a raktár eltűnik, így megelőzve hogy további hibás viselkedést produkáljon üresen ottmarad elemként. (Viszont a felvett számok megesik, hogy még mindig érdekesek, gyanúsan 40 közeli értéket vesznek fel, valami feltétel hiányára utalnak. Valószínűsítem, hogy loop-olódik a felvétel. Ennek meglétét és okát további vizsgálatokkal lehetne kideríteni.)

**Comment by Randomlosz** [comment]
Az előzőekben linkelt pull-request (#6) a 3. teszthez tartozó módosításokat tartalmazza.
