### ISSUE TITLE
Manuális kód átvizsgálás elvégzése az alkalmazás egy részére + Statikus analízis eszköz futtatása és jelzett hibák átnézése

### ISSUE THREAD

**Issue by Zykor111** [BME-MIT-IET/iet-hf-2023-syntax-spuad#4]
A feladat célja, hogy egyszer kézzel végigmenjünk egy kódrészleten, és ugyanezen a kódon egy tesztelő programot futtassunk, majd kijavítsuk az esetleges jelentős hibákat, ezáltal jobbá tenni a programot.

**Comment by diatrcz** [comment]
SonarLint alkalmazás segítségével árnéztem a code-behind részét az alkalmazásnak, és a szerintem is hibás részeket javítottam. Először átnéztem a Virologist osztályt, ahol a legtöbb hibát jelezte az alkalmazás. Itt változónevekkel volt sok problémája, mert szerinte nem voltak elég beszédesek. Ezen kívül rengeteg stringet újrahasználtunk, így a SonarLint javaslatára azokat is kiszerveztem statikus változókba újrafelhasználhatóság szempontjából. A metódusokat, amik nullal tértek vissza egyes helyzetekben átírtam, hogy üres objektumokkal térjenek vissza. A feleslegesen bennehagyott kikommentezett sorokat kitöröltem, hogy a kód esztétikusabban nézzen ki. Az egyik metódusban egy if ág véletlenül ;-vel volt lezárva, mivel utána egy break utasítás jött, így nem okozott valós problémát, de kijavítottam, hogy helyesen működjön.

**Comment by diatrcz** [comment]
Ezek után a többi osztályt is átnéztem, de csak kisebb problémákat találtam, így ezeket egybe foglalom össze. Sok egyáltalán nem használt, üres függvényt illetve változót töröltem az osztályokból. A kikommentezett sorokat itt is mindenhonnan kitöröltem, hogy ne zavarják a szemet. Hozzáadtam a függvényekhez a lemaradt annotációkat. 

Nem csak rengeteg üres/nem használt függvény volt, hanem rengeteg üres/nem használt fájl is, ezeket is kitöröltem az alkalmazásból, hogy csökkentsem a robosztusságát. 

A Random() létrehozást mindenhol kiszerveztem külön privát változóba, hogy ne kelljen minden egyes metódushívásnál újra létrehozni, és memóriát foglalni vele (ahogy gyakorlaton is csináltuk)

Ezen kívül még csináltam olyan egyszerű változásokat, mint az egymásra stackelt if-ek összekapcsolása. Így nem két if() van egymás alatt, hanem egy if(  &&  ), illetve ahol szükségét láttam/látta a SonarLint megváltoztattam a vátozók nevét is.

**Comment by Zykor111** [comment]
A SonarCloud statikus kód analízist adó program segítségével térképeztem fel a kódban, bugokat, és code smelleket.
Két nagyobb bugot találtam a programban az egyik az egy mindig a breakben végződő ciklus, ennek adtam egy feltételt. A másik pedig egy felcserélt getter, véletlen másik dolgot adtak vissza, mint amire a neve utal.
Codesmellek közül felesleges nem használt függvényeket, kódsorokat, init-eket, töröltem ott, ahol nem szükségesek. Volt olyan codesmell is, amit jelzett a SonarCloud, de egyértelműen helyes volt, ezt nem javítottam értelemszerűen.

**Comment by diatrcz** [comment]
A program UI részét adó kódokat is átnéztem SonarLint segítségével. Itt sokkal kevesebb hibát mutatott a kód analízis, de ezeket javítottam.
int i = 0;
for(int i = i, i < ..;  i++)-t kijavítottam szép for(int i =0...) kódra. A Cloak/Bag/Glove InventoryViewbann az ActionPerformed() metódusban mindenhol az if után lemaradt a kapcsoszárójel. Ez okozta, hogy míg a baltát le lehetett venni és el lehetett dobni a többi felszerelést nem. 

Ezen kívül csak kisebb változtatásokat végeztem, mint nem használt függvények/változók törlése, @Override annotációk hozzáadása, változók átnevezése.
